#!/usr/bin/python
import thread
import threading
from threading import Lock
import time

cv = Lock()
wheels = [True,True,True,True,True,True]
count = 0 
blocked = False
freeweeling = False
sinking = False

# Iterates through the array
def count_problems(threadName, delay):
    global count
    global blocked
    global freeweeling
    global sinking
    
    while 1:
     
     while blocked == True or freeweeling == True or sinking == True:
        cv.acquire()      
        count = count + 1
        print (threadName,"Number of problems",count) 
        time.sleep(delay)
        blocked = False
        freeweeling = False
        sinking = False   
        time.sleep(delay)
        cv.release() 
        break


def wheelss(threadName, delay):
    global blocked
    global freeweeling
    global sinking
    global wheels
    global x
    
    wheels = ["True","True","True","True","True","True"]     
    
    while 1:
    
      while blocked == True or freeweeling == True or sinking == True:
       cv.acquire()        
       x = input ("Enter the wheel with problem. Between 0-5: \n")
       while (x < 0) or (x >=6):
          print ("Error, the Roves has just 6 wheels 0-5")
          x = input ("Enter the wheels with problem: \n")    
       wheels[x] = "False"        
       for i in range(6):        
         print (threadName, wheels[i]) 
       time.sleep(delay)    
       cv.release()    
       wheels = ["True","True","True","True","True","True"]   
       break 

def solve(threadName, delay):
    global count
    global blocked
    global freeweeling
    global sinking
    
    while 1:
    
      while blocked != True or freeweeling != True or sinking != True:                              
        while 1:
            
            
            print(threadName, "Working")
            time.sleep(delay)
            
                     
            if blocked == True:
              cv.acquire()
              time.sleep(delay)
              print (threadName, "Problem solved")
              time.sleep(delay)
              blocked = False
              cv.release()
              break         
                
            if freeweeling == True:
              cv.acquire()
              time.sleep(delay)              
              print (threadName, "Problem solved")       
              time.sleep(delay)
              freeweeling = False
              cv.release()
              break
                
            if sinking == True:
              cv.acquire()
              time.sleep(delay)
              print (threadName, "Problem solved")
              time.sleep(delay)
              sinking = False
              cv.release()
              break
             
             

def problems(threadName,delay):
    global count
    global blocked
    global freeweeling
    global sinking
    
    
    while 1:

      cv.acquire()
      time.sleep(delay)
      command = raw_input("Enter the problem: b-blocked, f-freewheeling, s-sinking:\n")
      time.sleep(delay)
      cv.release()
       
      if command == "b": 
          cv.acquire()
          blocked = True   
          print("Wheel Blocked \n")
          time.sleep(delay)
          print (threadName, "Waiting to solve the problem")
          cv.release()
          time.sleep(delay)
                
      if command == "f":
          cv.acquire()
          freeweeling = True
          print("Wheel was freewheeling \n")
          time.sleep(delay)
          print (threadName, "Waiting to solve the problem")
          cv.release()
          time.sleep(delay)
          
      if command == "s":
          cv.acquire()
          sinking = True
          print("wheel was sinking \n")
          time.sleep(delay)
          print (threadName, "Waiting to solve the problem")
          cv.release()
          time.sleep(delay)
      
wheels = [True,True,True,True,True,True]
    

# Create three threads
try:
   t1 = thread.start_new_thread( problems, ("Thread-2",2 ) )
   t2 = thread.start_new_thread( solve, ("Thread-1", 2 ) )
   t3 = thread.start_new_thread( count_problems, ("Thread-3", 2 ) )
   t4 = thread.start_new_thread( wheelss, ("Thread-4", 2 ) )
   
except:
   print "Error: unable to start thread"

while 1:
   pass
